# Generated by Django 5.2.6 on 2025-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='query_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sql_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
